import { FormControl, RadioGroup, FormControlLabel, Radio, Button } from "@mui/material";
import Head from "next/head";
import { set, useForm } from "react-hook-form";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import fetchQuizz from '../../../lib/fetchQuizz'

export default function Quizz() {
  const [quizz, setQuizz] = useState()

  const router = useRouter()

  useEffect(() => {
    if(!router.query.id)  {
      return;
    }

    const getData = async () => {
      const jsonData = await fetchQuizz(router.query.id);
      setQuizz(jsonData)
    }
    getData()
  }, [router.query.id]);

  const { register, handleSubmit } = useForm({
    defaultValues: {
      whichLangIsThat: {
        questionNumber: "1",
        correctAnswer: "JavaScript"
      },
      whichLangSkeleton: {
        questionNumber: "2",
        correctAnswer: "HTML"
      }
    }
  });
  
  // const onSubmit = data => {
  //   const newData = JSON.stringify(data)
  //   router.push({
  //     pathname: '/results',
  //     query: { newData },
  //   }, '/results')
  // }
  return (
    <>
      <Head>
        <title>Quizzoto - Quizz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <main>
        {
          quizz?.statusCode ? (
            <p>Merci de fournir un id de quizz correct dans l'URL.</p>
          ) : quizz ? (
            <div>
              <h1>{quizz.quizzTitle}</h1>
              <h3>{quizz.quizzDescription}</h3>
            </div>
          ) : (
            <h2>Chargement...</h2>
          )
        }

      </main>
    </>
  );
}
