import { FormControl, RadioGroup, FormControlLabel, Radio, Button } from "@mui/material";
import Head from "next/head";
import { set, useForm } from "react-hook-form";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import fetchQuizz from '../../../lib/fetchQuizz'
import Question from "@/components/question";

export default function Quizz() {
  const [quizz, setQuizz] = useState()

  const router = useRouter()

  useEffect(() => {
    if(!router.query.id)  {
      return;
    }

    const getData = async () => {
      const jsonData = await fetchQuizz(router.query.id);
      setQuizz(jsonData)
    }
    getData()
  }, [router.query.id]);

  const { register, handleSubmit } = useForm();
  
  const onSubmit = data => {
    // const newData = JSON.stringify(data)
    // router.push({
    //   pathname: '/results',
    //   query: { newData },
    // }, '/results')
    console.log(data)
  }
  return (
    <>
      <Head>
        <title>Quizzoto - Quizz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <main>
        {
          quizz?.statusCode ? (
            <p>Merci de fournir un id de quizz correct dans l'URL.</p>
          ) : quizz ? (
            <div>
              <form onSubmit={handleSubmit(onSubmit)}>
                <h1>{quizz.quizzTitle}</h1>
                <h2>{quizz.quizzDescription}</h2>
                {
                  quizz.questions.map(q => {
                    return (
                      <div>
                        <h3>{q.questionTitle}</h3>
                        <Question question={q} register={register}/>
                      </div>
                    )
                  })
                }
                <Button type='submit' variant='contained'>Fin</Button>
              </form>
            </div>
          ) : (
            <h2>Chargement...</h2>
          )
        }

      </main>
    </>
  );
}
