import { FormControl, RadioGroup, FormControlLabel, Radio, Button } from "@mui/material";
import Head from "next/head";
import { useForm } from "react-hook-form";
import { useRouter } from "next/router";

export default function Quizz() {
  const { register, handleSubmit } = useForm({
    defaultValues: {
      whichLangIsThat: {
        questionNumber: "1",
        correctAnswer: "JavaScript"
      },
      whichLangSkeleton: {
        questionNumber: "2",
        correctAnswer: "HTML"
      }
    }
  });
  const router = useRouter()
  const onSubmit = data => {
    const newData = JSON.stringify(data)
    router.push({
      pathname: '/results',
      query: { newData },
    }, '/results')
  }
  return (
    <>
      <Head>
        <title>Quizzoto - Quizz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <main>
        <h1 style={{fontFamily: 'Roboto'}}>
          Le mega super quizz
        </h1>
        <form onSubmit={handleSubmit(onSubmit)}>

          <h2 style={{ fontFamily: 'Roboto'}}>De quel language est tiré ce bout de code : <code style={{ backgroundColor: 'grey', border: '2px solid'}}>console.log("Hello World")</code></h2>

          <FormControl>
            <RadioGroup
              aria-labelledby="demo-radio-buttons-group-label"
              defaultValue="female"
              name="radio-buttons-group"
            >
              <FormControlLabel {...register("whichLangIsThat.answer", {
                required: true
              })} value="Java" control={<Radio />} label="Java" />
              <FormControlLabel {...register("whichLangIsThat.answer", {
                required: true
              })} value="Python" control={<Radio />} label="Python" />
              <FormControlLabel {...register("whichLangIsThat.answer", {
                required: true
              })} value="JavaScript" control={<Radio />} label="JavaScript" />
            </RadioGroup>
          </FormControl>

          <h2 style={{ fontFamily: 'Roboto'}}>Quel language est utilsié pour créer le "squelette" d'un site internet</h2>

          <FormControl>
            <RadioGroup
              aria-labelledby="demo-radio-buttons-group-label"
              defaultValue="female"
              name="radio-buttons-group"
            >
              <FormControlLabel {...register("whichLangSkeleton.answer", {
                required: true
              })} value="CSS" control={<Radio />} label="CSS" />
              <FormControlLabel {...register("whichLangSkeleton.answer", {
                required: true
              })} value="HTML" control={<Radio />} label="HTML" />
            </RadioGroup>
          </FormControl>
          <div>
            <Button type="submit" variant="contained">Soumettre</Button>
          </div>
        </form>
      </main>
    </>
  );
}
