version: '3.1'

services:
    quizzoto_db:
        image: mongo
        restart: always
        container_name: quizzotoDB
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: quizzoto
        # networks:
        #     - quizzoto_network
        network_mode: host
        ports:
            - 27017:27017
        volumes:
            - ./data/mongo:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    quizzoto_web:
        image: node:latest
        container_name: quizzoto
        command: /bin/sh -c "cd /srv/app && npm install && npm run dev"
        ports:
            - 3000:3000
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
        network_mode: host
        # networks:
        #     - quizzoto_network
# networks:
#     quizzoto_network:
