db = db.getSiblingDB('quizzoto');

db.createCollection('results');
db.createCollection('quizzs');

db.quizzs.insert([
	{
		quizzTitle: 'Super quizz',
		quizzDescription: 'Ce super quizz pose des questions sur le super groupe ISAS-FSD.',
		questions: [
			{
				questionTitle: 'Qui est le meilleur développeur React du monde ?',
				questionType: 'radios',
				answers: ['Azecko', 'JaavLex', 'Ponsfrilus', 'Dwesh163'],
				correctAnswer: 'Dwesh163',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: 'Qui a participé aux RegionalsSkills 2023 ?',
				questionType: 'checkboxes',
				answers: ['Emyxi', 'JaavLex', 'Pyrosaphire', 'Azecko'],
				correctAnswer: ['Emyxi', 'Azecko'],
				pointsIfCorrect: 2,
				minusPointsIfWrong: 0,
			},
			{
				questionTitle: 'Quel est le language de programmation que multiscan déteste ?',
				questionType: 'textfield',
				correctAnswer: ['javascript', 'js'],
				pointsIfCorrect: 2,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: 'Quel framework est principalement utilisé pour le développement mobile ?',
				questionType: 'radios',
				answers: ['React Native', 'Angular', 'Vue.js', 'Flutter'],
				correctAnswer: 'React Native',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: 'Quel est le langage de programmation le plus utilisé pour le développement web côté serveur ?',
				questionType: 'radios',
				answers: ['JavaScript', 'Python', 'Java', 'PHP'],
				correctAnswer: 'JavaScript',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: 'Quelle méthode HTTP est utilisée pour envoyer des données à un serveur web ?',
				questionType: 'radios',
				answers: ['GET', 'POST', 'PUT', 'DELETE'],
				correctAnswer: 'POST',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: 'Quel est le protocole utilisé pour transférer des données sur le Web de manière sécurisée ?',
				questionType: 'radios',
				answers: ['HTTP', 'FTP', 'HTTPS', 'SMTP'],
				correctAnswer: 'HTTPS',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: 'Quelle est la signification de JSON ?',
				questionType: 'radios',
				answers: ['JavaScript Object Notation', 'Java Serialized Object Notation', 'JavaScript Serialized Object Notation', 'JavaScript Oriented Notation'],
				correctAnswer: 'JavaScript Object Notation',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: 'Quel est le paradigme de programmation principalement utilisé dans la programmation fonctionnelle ?',
				questionType: 'radios',
				answers: ['Impératif', 'Déclaratif', 'Orienté objet', 'Logique'],
				correctAnswer: 'Déclaratif',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: "Quel est le principal avantage de l'utilisation des fonctions fléchées en JavaScript ?",
				questionType: 'radios',
				answers: ['Elles sont plus courtes à écrire', 'Elles préservent le contexte de "this"', 'Elles sont plus performantes', 'Elles sont compatibles avec tous les navigateurs'],
				correctAnswer: 'Elles préservent le contexte de "this"',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: 'Quel est le principal rôle de Git dans le développement de logiciels ?',
				questionType: 'radios',
				answers: ['Suivi des bugs', 'Gestion des dépendances', 'Contrôle de version', 'Tests automatisés'],
				correctAnswer: 'Contrôle de version',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: 'Quelle est la signification de HTML ?',
				questionType: 'radios',
				answers: ['Hyper Text Markup Language', 'Hyperlinks and Text Markup Language', 'Home Tool Markup Language', 'Hyperlinks Text Makeup Language'],
				correctAnswer: 'Hyper Text Markup Language',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: "Quel est le principal avantage de l'utilisation de l'approche Agile en développement logiciel ?",
				questionType: 'radios',
				answers: ['Planification détaillée', 'Livraison continue de logiciels fonctionnels', 'Strict respect des délais', 'Documentation exhaustive'],
				correctAnswer: 'Livraison continue de logiciels fonctionnels',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: "Quel est le principal avantage de l'utilisation de Docker dans le développement logiciel ?",
				questionType: 'radios',
				answers: ['Isolation des applications', 'Optimisation des requêtes SQL', 'Déploiement sur des serveurs virtuels', 'Automatisation des tests unitaires'],
				correctAnswer: 'Isolation des applications',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: 'Quelle est la différence principale entre HTTP et HTTPS ?',
				questionType: 'radios',
				answers: ['La sécurité des données', 'La méthode de transfert des données', 'Le port utilisé', 'La taille maximale des données transférées'],
				correctAnswer: 'La sécurité des données',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: "Qu'est-ce que le modèle MVC dans le développement web ?",
				questionType: 'radios',
				answers: ['Model View Component', 'Modular View Control', 'Model View Controller', 'Modular View Component'],
				correctAnswer: 'Model View Controller',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: "Quel est le principal avantage de l'utilisation de TypeScript par rapport à JavaScript ?",
				questionType: 'radios',
				answers: ['Syntaxe plus concise', 'Typage statique', 'Exécution plus rapide', 'Meilleure compatibilité avec les navigateurs'],
				correctAnswer: 'Typage statique',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
			{
				questionTitle: "Quelle est la méthode la plus efficace pour optimiser les performances d'un site web ?",
				questionType: 'radios',
				answers: ['Minification des fichiers CSS et JavaScript', 'Augmentation de la résolution des images', 'Ajout de plus de contenu multimédia', 'Utilisation de plusieurs serveurs'],
				correctAnswer: 'Minification des fichiers CSS et JavaScript',
				pointsIfCorrect: 1,
				minusPointsIfWrong: 1,
			},
		],
	},
]);

db.createUser({
	user: process.env.MONGO_INITDB_USER_USERNAME,
	pwd: process.env.MONGO_INITDB_USER_PASSWORD,
	roles: [{ role: 'readWrite', db: process.env.MONGO_INITDB_DATABASE }],
});
