import { Typography, Button } from '@mui/material';
import Head from 'next/head';

import Header from '../components/header/header';

export default function Home() {
	console.log('lollol');
	return (
		<>
			<Head>
				<title>Quizzoto - Accueil</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="stylesheet" href="/index.css" />
				<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
			</Head>
			<main>
				<Header />
				<h1 style={{ fontFamily: 'Roboto' }}>Quizzoto - Quizz super basique</h1>
				<Button href="/quizz" variant="contained" style={{ backgroundColor: 'purple' }}>
					Quizz
				</Button>
			</main>
		</>
	);
}
